version: "3.9"
services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - "27017:27017"
    command: --smallfiles
  app:
    image: hendisantika/student-service
    ports:
      - "8080:8080"
    links:
      - mongodb
